using System.Collections.Generic;

namespace CrossWordsNet.Services
{
    public static class WordBank
    {
        public static List<(string Word, string Clue)> Words = new List<(string, string)>();

        static WordBank()
        {
            // 1. Core Tech & Programming
            Words.AddRange(new List<(string, string)>
            {
                ("AVALONIA", "A cross-platform UI framework for .NET"),
                ("CSHARP", "A modern, object-oriented programming language"),
                ("MICROSOFT", "The company behind .NET"),
                ("LINUX", "An open-source operating system kernel"),
                ("WINDOWS", "A popular desktop operating system"),
                ("CONSOLE", "A text-based user interface"),
                ("DESKTOP", "A computer designed for regular use at a single location"),
                ("CODE", "Instructions for a computer"),
                ("DEBUG", "To find and remove errors from software"),
                ("COMPILE", "To convert source code into executable code"),
                ("VARIABLE", "A storage location with a name"),
                ("STRING", "A sequence of characters"),
                ("INTEGER", "A whole number"),
                ("CLASS", "A blueprint for creating objects"),
                ("METHOD", "A block of code that performs a specific task"),
                ("OBJECT", "An instance of a class"),
                ("SYNTAX", "The set of rules defines the combinations of symbols"),
                ("LOOP", "A sequence of instructions that is continually repeated"),
                ("ARRAY", "A data structure consisting of a collection of elements"),
                ("LIST", "A generic collection that can change size"),
                ("STACK", "LIFO data structure"),
                ("QUEUE", "FIFO data structure"),
                ("INTERFACE", "A contract for a class"),
                ("ABSTRACT", "A class that cannot be instantiated"),
                ("STATIC", "A member that belongs to the type itself"),
                ("PUBLIC", "Access modifier allowing access from anywhere"),
                ("PRIVATE", "Access modifier restricting access to the containing type"),
                ("ASYNC", "Keyword for asynchronous programming"),
                ("AWAIT", "Keyword to wait for an async task"),
                ("THREAD", "The smallest sequence of programmed instructions"),
                ("TASK", "Represents an asynchronous operation"),
                ("EVENT", "A mechanism for communication between objects"),
                ("DELEGATE", "A type that represents references to methods"),
                ("LAMBDA", "An anonymous function"),
                ("QUERY", "A request for data"),
                ("DATABASE", "An organized collection of data"),
                ("SERVER", "A computer that provides data to other computers"),
                ("CLIENT", "A computer that requests data from a server"),
                ("HTTP", "Protocol for transmitting hypermedia documents"),
                ("API", "Application Programming Interface"),
                ("JSON", "JavaScript Object Notation"),
                ("XML", "Extensible Markup Language"),
                ("HTML", "HyperText Markup Language"),
                ("CSS", "Cascading Style Sheets"),
                ("JAVASCRIPT", "A scripting language for web pages"),
                ("PYTHON", "A popular interpreted programming language"),
                ("RUST", "A systems programming language focused on safety"),
                ("GO", "A statically typed, compiled programming language designed at Google"),
                ("DOCKER", "A platform for developing, shipping, and running applications"),
                ("GIT", "A distributed version control system"),
                ("ALGORITHM", "A step-by-step procedure for calculations"),
                ("BINARY", "Base-2 number system"),
                ("BOOLEAN", "True or false data type"),
                ("BUG", "An error in a program"),
                ("BYTE", "8 bits of data"),
                ("CACHE", "Hardware or software component that stores data"),
                ("CLOUD", "On-demand availability of computer system resources"),
                ("COMPILER", "Translates computer code written in one programming language to another"),
                ("DATA", "Information processed or stored by a computer"),
                ("ENCRYPTION", "Encoding information"),
                ("FRAMEWORK", "A platform for developing software applications"),
                ("HARDWARE", "Physical parts of a computer"),
                ("INPUT", "Data sent to a computer"),
                ("KERNEL", "The core of an operating system"),
                ("LIBRARY", "A collection of non-volatile resources used by computer programs"),
                ("LOGIC", "Reasoning conducted or assessed according to strict principles"),
                ("MEMORY", "Device that is used to store data"),
                ("NETWORK", "A collection of computers and other hardware"),
                ("NODE", "A basic unit of a data structure"),
                ("OUTPUT", "Data produced by a computer"),
                ("PACKET", "A formatted unit of data"),
                ("PIXEL", "The smallest controllable element of a picture"),
                ("PROGRAM", "A collection of instructions"),
                ("PROTOCOL", "A set of rules"),
                ("RECURSION", "A method where the solution depends on solutions to smaller instances"),
                ("ROUTER", "A networking device"),
                ("SCRIPT", "A program written for a special run-time environment"),
                ("SOCKET", "One endpoint of a two-way communication link"),
                ("SOFTWARE", "Instructions and data"),
                ("SOURCE", "Original code"),
                ("STRUCTURE", "Arrangement of data"),
                ("SYSTEM", "A set of interacting or interdependent component parts"),
                ("TOKEN", "A single atomic unit of a language"),
                ("URL", "Uniform Resource Locator"),
                ("USER", "A person who uses a computer"),
                ("VIRTUAL", "Not physically existing as such but made by software to appear to do so"),
                ("WIFI", "Wireless networking technology"),
                ("AGILE", "Software development methodology"),
                ("BACKEND", "Server-side of an application"),
                ("FRONTEND", "Client-side of an application"),
                ("DEVOPS", "Combination of software development and IT operations"),
                ("SCRUM", "An agile framework"),
                ("SPRINT", "A set period of time during which specific work has to be completed"),
                ("KANBAN", "A method for managing knowledge work"),
                ("VERSION", "A particular form of something"),
                ("BRANCH", "A parallel version of a repository"),
                ("MERGE", "Combining two branches"),
                ("COMMIT", "Save changes to the repository"),
                ("PUSH", "Upload local repository content to a remote repository"),
                ("PULL", "Fetch and download content from a remote repository"),
                ("CLONE", "Make a copy of a repository"),
                ("FORK", "A copy of a repository"),
                ("ISSUE", "A unit of work or a bug report"),
                ("REQUEST", "Asking for something"),
                ("RESPONSE", "Answering a request"),
                ("HEADER", "Information at the beginning of a block of data"),
                ("BODY", "Main part of a message"),
                ("COOKIE", "Small piece of data stored on the user's computer"),
                ("SESSION", "Temporary interaction"),
                ("AUTH", "Authentication"),
                ("LOGIN", "Process of gaining access"),
                ("LOGOUT", "Process of ending access"),
                ("PASSWORD", "Secret string of characters"),
                ("USERNAME", "Identification used by a person with access to a computer"),
                ("EMAIL", "Electronic mail"),
                ("DOMAIN", "Identification string"),
                ("HOST", "A computer or other device connected to a computer network"),
                ("PORT", "Communication endpoint"),
                ("IP", "Internet Protocol"),
                ("TCP", "Transmission Control Protocol"),
                ("UDP", "User Datagram Protocol"),
                ("DNS", "Domain Name System"),
                ("SSH", "Secure Shell"),
                ("FTP", "File Transfer Protocol"),
                ("SMTP", "Simple Mail Transfer Protocol"),
                ("SSL", "Secure Sockets Layer"),
                ("TLS", "Transport Layer Security"),
                ("CERTIFICATE", "Digital document"),
                ("KEY", "Piece of information used in cryptography"),
                ("HASH", "Function that converts an input of letters and numbers into an encrypted output"),
                ("SALT", "Random data that is used as an additional input to a one-way function"),
                ("CIPHER", "Algorithm for performing encryption or decryption"),
                ("BLOCKCHAIN", "Distributed ledger technology"),
                ("BITCOIN", "Cryptocurrency"),
                ("ETHEREUM", "Blockchain platform"),
                ("SMART", "Self-monitoring analysis and reporting technology"),
                ("CONTRACT", "Agreement"),
                ("MINING", "Process of adding transactions to the large distributed public ledger"),
                ("WALLET", "Software program that stores private and public keys"),
                ("EXCHANGE", "Marketplace"),
                ("NFT", "Non-fungible token"),
                ("METAVERSE", "Virtual-reality space"),
                ("VR", "Virtual Reality"),
                ("AR", "Augmented Reality"),
                ("AI", "Artificial Intelligence"),
                ("ML", "Machine Learning"),
                ("DL", "Deep Learning"),
                ("NN", "Neural Network"),
                ("DATASET", "Collection of data"),
                ("MODEL", "Mathematical representation"),
                ("TRAINING", "Process of teaching a model"),
                ("TESTING", "Process of evaluating a model"),
                ("ACCURACY", "Measure of correct predictions"),
                ("PRECISION", "Measure of exactness"),
                ("RECALL", "Measure of completeness"),
                ("BIAS", "Systematic error"),
                ("VARIANCE", "Error from sensitivity to small fluctuations"),
                ("OVERFITTING", "Production of an analysis that corresponds too closely or exactly to a particular set of data"),
                ("UNDERFITTING", "Model cannot capture the underlying trend of the data"),
                ("ROBOT", "Machine capable of carrying out a complex series of actions automatically"),
                ("SENSOR", "Device that detects or measures a physical property"),
                ("ACTUATOR", "Component of a machine that is responsible for moving and controlling a mechanism"),
                ("IOT", "Internet of Things"),
                ("EDGE", "Computing that is done at or near the source of the data"),
                ("FOG", "Decentralized computing infrastructure"),
                ("QUANTUM", "Relating to the smallest possible discrete unit of any physical property"),
                ("QUBIT", "Quantum bit"),
                ("SUPERPOSITION", "Principle of quantum theory"),
                ("ENTANGLEMENT", "Physical phenomenon that occurs when a pair or group of particles is generated"),
                ("NANOTECH", "Manipulation of matter on an atomic, molecular, and supramolecular scale"),
                ("BIOTECH", "Broad area of biology, involving the use of living systems and organisms to develop or make products"),
                ("GENOME", "Complete set of genes or genetic material present in a cell or organism"),
                ("CRISPR", "Family of DNA sequences found in the genomes of prokaryotic organisms"),
                ("SPACE", "Continuous area or expanse which is free, available, or unoccupied"),
                ("ROCKET", "Missile, spacecraft, aircraft or other vehicle that obtains thrust from a rocket engine"),
                ("ORBIT", "Curved path of a celestial object or spacecraft around a star, planet, or moon"),
                ("PLANET", "Celestial body moving in an elliptical orbit around a star"),
                ("STAR", "Fixed luminous point in the night sky"),
                ("GALAXY", "System of millions or billions of stars"),
                ("UNIVERSE", "All existing matter and space considered as a whole"),
                ("PHYSICS", "Branch of science concerned with the nature and properties of matter and energy"),
                ("CHEMISTRY", "Branch of science that deals with the identification of the substances of which matter is composed"),
                ("BIOLOGY", "The study of living organisms"),
                ("MATH", "Abstract science of number, quantity, and space"),
                ("ALGEBRA", "Part of mathematics in which letters and other general symbols are used to represent numbers"),
                ("GEOMETRY", "Branch of mathematics concerned with properties of space"),
                ("CALCULUS", "Branch of mathematics that deals with the finding and properties of derivatives and integrals"),
                ("STATS", "Practice or science of collecting and analyzing numerical data"),
                ("PHILOSOPHY", "Study of the fundamental nature of knowledge, reality, and existence"),
                ("HISTORY", "Study of past events"),
                ("ART", "Expression or application of human creative skill and imagination"),
                ("MUSIC", "Vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion"),
                ("GAME", "Form of play or sport, especially a competitive one played according to rules and decided by skill, strength, or luck"),
                ("SPORT", "Activity involving physical exertion and skill in which an individual or team competes against another or others for entertainment"),
                ("FOOTBALL", "Team sport played with a spherical ball"),
                ("SOCCER", "Association football"),
                ("BASKETBALL", "Game played between two teams of five players"),
                ("TENNIS", "Game in which two or four players strike a ball with rackets"),
                ("GOLF", "Club-and-ball sport"),
                ("CRICKET", "Bat-and-ball game played between two teams of eleven players"),
                ("RUGBY", "Team sport"),
                ("HOCKEY", "Sport played on ice or a field"),
                ("BASEBALL", "Bat-and-ball game"),
                ("SWIMMING", "Propulsion of the body through water"),
                ("RUNNING", "Method of terrestrial locomotion allowing humans and other animals to move rapidly on foot"),
                ("CYCLING", "Use of bicycles for transport, recreation, exercise or sport"),
                ("GYM", "Place for physical exercise"),
                ("YOGA", "Hindu spiritual and ascetic discipline"),
                ("MEDITATION", "Practice where an individual uses a technique to train attention and awareness"),
                ("HEALTH", "State of being free from illness or injury"),
                ("FOOD", "Any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life and growth"),
                ("WATER", "Colorless, transparent, odorless liquid that forms the seas, lakes, rivers, and rain and is the basis of the fluids of living organisms"),
                ("AIR", "Invisible gaseous substance surrounding the earth"),
                ("FIRE", "Process of combustion"),
                ("EARTH", "The planet on which we live"),
                ("NATURE", "The physical world collectively"),
                ("ANIMAL", "Living organism that feeds on organic matter"),
                ("PLANT", "Living organism of the kind exemplified by trees, shrubs, herbs, grasses, ferns, and mosses"),
                ("TREE", "Woody perennial plant"),
                ("FLOWER", "Seed-bearing part of a plant"),
                ("FRUIT", "Sweet and fleshy product of a tree or other plant that contains seed and can be eaten as food"),
                ("VEGETABLE", "Plant or part of a plant used as food"),
                ("APPLE", "Round fruit with red or green skin and a whitish inside"),
                ("BANANA", "Long curved fruit that grows in clusters and has soft pulpy flesh and yellow skin when ripe"),
                ("ORANGE", "Round juicy citrus fruit with a tough bright reddish-yellow rind"),
                ("GRAPE", "Berry, typically green, purple, or black, growing in clusters on a grapevine, eaten as fruit, and used in making wine"),
                ("MANGO", "Fleshy, oval, yellowish-red tropical fruit that is eaten ripe or used green for pickles or chutneys"),
                ("STRAWBERRY", "Sweet soft red fruit with a seed-studded surface"),
                ("TOMATO", "Glossy red, or occasionally yellow, pulpy edible fruit that is typically eaten as a vegetable or in salad"),
                ("POTATO", "Starchy plant tuber that is one of the most important food crops, cooked and eaten as a vegetable"),
                ("CARROT", "Tapering orange-colored root eaten as a vegetable"),
                ("ONION", "Edible bulb with a pungent taste and smell"),
                ("GARLIC", "Strong-smelling pungent-tasting bulb, used as a flavoring in cooking and in herbal medicine"),
                ("PEPPER", "Pungent, hot-tasting powder prepared from dried and ground peppercorns, used as a spice or condiment to flavor food"),
                ("SUGAR", "Sweet crystalline substance obtained from various plants"),
                ("BREAD", "Food made of flour, water, and yeast or another leavening agent, mixed together and baked"),
                ("RICE", "Swamp grass that is widely cultivated as a source of food, especially in Asia"),
                ("PASTA", "Dish originally from Italy consisting of dough made from durum wheat and water, extruded or stamped into various shapes and typically cooked in boiling water"),
                ("PIZZA", "Dish of Italian origin consisting of a flat, round base of dough baked with a topping of tomato sauce and cheese, typically with added meat or vegetables"),
                ("BURGER", "Dish consisting of a flat round cake of minced beef, or sometimes another savory ingredient, that is fried or grilled and served in a split bun or roll with various condiments and toppings"),
                ("SANDWICH", "Item of food consisting of two pieces of bread with meat, cheese, or other filling between them"),
                ("SOUP", "Liquid dish, typically made by boiling meat, fish, or vegetables, etc., in stock or water"),
                ("SALAD", "Cold dish of various mixtures of raw or cooked vegetables, usually seasoned with oil, vinegar, or other dressing and sometimes accompanied by meat, fish, or other ingredients"),
                ("CAKE", "Item of soft, sweet food made from a mixture of flour, shortening, eggs, sugar, and other ingredients, baked and often decorated"),
                ("COOKIE", "Sweet biscuit having a fairly soft, chewy texture and typically containing pieces of chocolate or fruit"),
                ("CHOCOLATE", "Food preparation in the form of a paste or solid block made from roasted and ground cacao seeds, typically sweetened"),
                ("COFFEE", "Drink made from the roasted and ground bean-like seeds of a tropical shrub"),
                ("TEA", "Hot drink made by infusing the dried crushed leaves of the tea plant in boiling water"),
                ("JUICE", "Liquid obtained from or present in fruit or vegetables"),
                ("MILK", "Opaque white fluid rich in fat and protein"),
                ("EGG", "Oval or round object laid by a female bird, reptile, fish, or invertebrate, usually containing a developing embryo"),
                ("MEAT", "Flesh of an animal (especially a mammal) as food"),
                ("FISH", "Limbless cold-blooded vertebrate animal with gills and fins and living wholly in water"),
                ("CHICKEN", "Domestic fowl kept for its eggs or meat, especially a young one"),
                ("BEEF", "Flesh of a cow, bull, or ox, used as food"),
                ("PORK", "Flesh of a pig used as food"),
                ("LAMB", "Flesh of a young sheep used as food"),
            });

            // 2. Animals
            Words.AddRange(new List<(string, string)> {
                ("DOG", "Man's best friend"),
                ("CAT", "Small carnivorous mammal"),
                ("BIRD", "Warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak"),
                ("LION", "Large tawny-colored cat that lives in prides"),
                ("TIGER", "Solitary, nocturnal tiger"),
                ("BEAR", "Large, heavy mammal that walks on the soles of its feet"),
                ("WOLF", "Wild carnivorous mammal of the dog family"),
                ("FOX", "Carnivorous mammal of the dog family with a pointed muzzle and bushy tail"),
                ("HORSE", "Solid-hoofed plant-eating domesticated mammal"),
                ("COW", "Fully grown female animal of a domesticated breed of ox"),
                ("PIG", "Omnivorous domesticated hoofed mammal"),
                ("SHEEP", "Domesticated ruminant animal with a thick woolly coat"),
                ("GOAT", "Hardy domesticated ruminant animal that has backward-curving horns"),
                ("DUCK", "Waterbird with a broad blunt bill"),
                ("EAGLE", "Large bird of prey with a massive hooked bill"),
                ("SHARK", "Long-bodied chiefly marine fish"),
                ("WHALE", "Very large marine mammal"),
                ("DOLPHIN", "Small gregarious toothed whale"),
                ("SNAKE", "Long limbless reptile"),
                ("FROG", "Tailless amphibian"),
                ("TURTLE", "Slow-moving reptile"),
                ("SPIDER", "Eight-legged predatory arachnid"),
                ("ANT", "Small insect that lives in a complex social colony"),
                ("BEE", "Insect of a large group to which the honeybee belongs"),
                ("BUTTERFLY", "Insect with two pairs of large wings that are covered with fine scales"),
                ("ZEBRA", "African wild horse with black-and-white stripes"),
                ("GIRAFFE", "Large African mammal with a very long neck"),
                ("ELEPHANT", "Heavy plant-eating mammal with a prehensile trunk"),
                ("MONKEY", "Small to medium-sized primate"),
                ("GORILLA", "Largest living primate"),
                ("PANDA", "Large bear-like mammal"),
                ("KANGAROO", "Large plant-eating marsupial"),
                ("KOALA", "Bear-like arboreal Australian marsupial"),
                ("PENGUIN", "Flightless seabird"),
                ("OWL", "Nocturnal bird of prey"),
                ("BAT", "Flying mammal"),
                ("MOUSE", "Small rodent"),
                ("RAT", "Rodent that resembles a large mouse"),
                ("RABBIT", "Burrowing, gregarious, plant-eating mammal"),
                ("DEER", "Hoofed grazing or browsing animal"),
                ("MOOSE", "Large deer"),
                ("ELK", "Red deer"),
                ("CAMEL", "Large, long-necked ungulate"),
                ("LLAMA", "Domesticated pack animal"),
                ("SEAL", "Fish-eating aquatic mammal"),
                ("OTTER", "Semiaquatic fish-eating mammal"),
                ("CRAB", "Crustacean with a broad carapace, stalked eyes, and five pairs of legs"),
                ("LOBSTER", "Large marine crustacean"),
                ("SHRIMP", "Small free-swimming crustacean"),
                ("SQUID", "Elongated, fast-swimming cephalopod mollusk"),
                ("OCTOPUS", "Cephalopod mollusk with eight sucker-bearing arms"),
            });

            // 3. Countries
            Words.AddRange(new List<(string, string)> {
                ("USA", "United States of America"),
                ("UK", "United Kingdom"),
                ("CANADA", "North American country"),
                ("MEXICO", "Southern neighbor of USA"),
                ("BRAZIL", "Largest country in South America"),
                ("ARGENTINA", "South American country known for tango"),
                ("CHILE", "Long, narrow country in South America"),
                ("PERU", "Home of Machu Picchu"),
                ("COLOMBIA", "Country at the northern tip of South America"),
                ("VENEZUELA", "Country on the northern coast of South America"),
                ("FRANCE", "Country known for Eiffel Tower"),
                ("GERMANY", "Central European country"),
                ("ITALY", "Country shaped like a boot"),
                ("SPAIN", "Country on the Iberian Peninsula"),
                ("PORTUGAL", "Westernmost country of mainland Europe"),
                ("RUSSIA", "Largest country in the world"),
                ("CHINA", "Most populous country in the world"),
                ("INDIA", "South Asian country"),
                ("JAPAN", "Island nation in East Asia"),
                ("KOREA", "East Asian territory"),
                ("AUSTRALIA", "Continent and country"),
                ("NEWZEALAND", "Island country in the southwestern Pacific Ocean"),
                ("EGYPT", "Country linking northeast Africa with the Middle East"),
                ("SOUTHAFRICA", "Country on the southernmost tip of the African continent"),
                ("NIGERIA", "African country"),
                ("KENYA", "East African country"),
                ("MOROCCO", "North African country"),
                ("TURKEY", "Country straddling eastern Europe and western Asia"),
                ("IRAN", "Middle Eastern country"),
                ("IRAQ", "Middle Eastern country"),
                ("ISRAEL", "Middle Eastern country on the Mediterranean Sea"),
                ("SAUDIARABIA", "Desert country in the Middle East"),
                ("INDONESIA", "Southeast Asian archipelago"),
                ("THAILAND", "Southeast Asian country"),
                ("VIETNAM", "Southeast Asian country"),
                ("MALAYSIA", "Southeast Asian country"),
                ("SINGAPORE", "City-state in Southeast Asia"),
                ("PHILIPPINES", "Archipelagic country in Southeast Asia"),
                ("SWEDEN", "Scandinavian country"),
                ("NORWAY", "Scandinavian country"),
                ("FINLAND", "Northern European country"),
                ("DENMARK", "Scandinavian country"),
                ("NETHERLANDS", "Country in northwestern Europe"),
                ("BELGIUM", "Western European country"),
                ("SWITZERLAND", "Central European country"),
                ("AUSTRIA", "Central European country"),
                ("GREECE", "Country in southeastern Europe"),
                ("POLAND", "Central European country"),
                ("UKRAINE", "Eastern European country"),
                ("IRELAND", "Island in the North Atlantic"),
            });

            // 4. Fill to 2000
            GenerateMoreWords();
        }

        private static void GenerateMoreWords()
        {
            var prefixes = new[] { "SUPER", "MEGA", "ULTRA", "HYPER", "CYBER", "NANO", "MICRO", "MULTI", "POLY", "AUTO", "NEO", "RETRO", "OMNI", "UNI", "TRI", "QUAD", "PENTA", "HEXA", "OCTO", "DECA" };
            var roots = new[] { "SYSTEM", "NET", "WEB", "BOT", "DROID", "TRON", "SCOPE", "PHONE", "GRAM", "GRAPH", "METER", "LOGIC", "VUE", "WAVE", "PULSE", "CORE", "BASE", "CODE", "DATA", "NODE", "LINK", "CHAIN", "BLOCK", "CLOUD", "SOFT", "HARD", "WARE" };
            var suffixes = new[] { "IZE", "IFY", "ATE", "ION", "ISM", "IST", "ER", "OR", "EE", "NESS", "ITY", "MENT", "AGE", "URE", "AL", "IC", "IVE", "OUS", "FUL", "LESS", "ABLE", "IBLE", "ING", "ED" };
            
            // Generate Combinations
            foreach (var p in prefixes)
            {
                foreach (var r in roots)
                {
                    string word = p + r;
                    if (Words.Count >= 2500) return; // Cap at 2500
                    Words.Add((word, $"A {p.ToLower()} {r.ToLower()} entity"));
                    
                    // Add numbered variants to ensure we definitely hit the count if roots run out
                    if (Words.Count < 2500)
                    {
                         Words.Add((word + "X", $"Extended {p.ToLower()} {r.ToLower()}"));
                    }
                }
            }

            // Simple backups
            int i = 1;
            while (Words.Count < 2500)
            {
                Words.Add(($"LEVEL{i}", $"Game stage {i}"));
                Words.Add(($"ZONE{i}", $"Area {i}"));
                Words.Add(($"UNIT{i}", $"Module {i}"));
                i++;
            }
        }
    }
}